-- V4 ETH/XRP tickformer runtime overrides (n>=20, wilson_low>=0.7)
-- Generated 2026-06-02T11:25:22.485874  from tf_v4_pocket_sweep.json
-- Total override rows: 49  (max-wilson per asset×variant×band×side)
-- ALL rows shadow_only=1 per feedback_no_auto_promote
-- Source hub note: #823. Runbook: #818 UPDATE 3.

BEGIN;

-- ETH v16 100-140 DN  n=22 WR=1.000 wl=0.851
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v16_pure_eth', 'ETH', '100-140', 'DN', 0.88, 1, 823, 22, 1.0000, 0.8513, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- ETH v16 100-140 UP  n=119 WR=0.941 wl=0.884
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v16_pure_eth', 'ETH', '100-140', 'UP', 0.8, 1, 823, 119, 0.9412, 0.8835, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- ETH v16 160-180 DN  n=26 WR=0.962 wl=0.811
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v16_pure_eth', 'ETH', '160-180', 'DN', 0.86, 1, 823, 26, 0.9615, 0.8111, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- ETH v16 160-180 UP  n=186 WR=0.796 wl=0.732
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v16_pure_eth', 'ETH', '160-180', 'UP', 0.66, 1, 823, 186, 0.7957, 0.7320, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- ETH v16 200-220 DN  n=101 WR=0.832 wl=0.747
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v16_pure_eth', 'ETH', '200-220', 'DN', 0.74, 1, 823, 101, 0.8317, 0.7469, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- ETH v16 60-80 DN  n=33 WR=1.000 wl=0.896
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v16_pure_eth', 'ETH', '60-80', 'DN', 0.9, 1, 823, 33, 1.0000, 0.8957, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- ETH v16 60-80 UP  n=99 WR=0.970 wl=0.915
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v16_pure_eth', 'ETH', '60-80', 'UP', 0.84, 1, 823, 99, 0.9697, 0.9147, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- ETH v17 100-140 DN  n=175 WR=0.903 wl=0.850
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v17_sniper_eth', 'ETH', '100-140', 'DN', 0.72, 1, 823, 175, 0.9029, 0.8499, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- ETH v17 100-140 UP  n=134 WR=0.918 wl=0.859
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v17_sniper_eth', 'ETH', '100-140', 'UP', 0.82, 1, 823, 134, 0.9179, 0.8590, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- ETH v17 160-180 DN  n=30 WR=0.967 wl=0.833
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v17_sniper_eth', 'ETH', '160-180', 'DN', 0.84, 1, 823, 30, 0.9667, 0.8333, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- ETH v17 160-180 UP  n=155 WR=0.787 wl=0.716
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v17_sniper_eth', 'ETH', '160-180', 'UP', 0.76, 1, 823, 155, 0.7871, 0.7161, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- ETH v17 200-220 DN  n=129 WR=0.822 wl=0.747
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v17_sniper_eth', 'ETH', '200-220', 'DN', 0.64, 1, 823, 129, 0.8217, 0.7467, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- ETH v17 60-80 DN  n=62 WR=0.952 wl=0.867
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v17_sniper_eth', 'ETH', '60-80', 'DN', 0.88, 1, 823, 62, 0.9516, 0.8671, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- ETH v17 60-80 UP  n=64 WR=0.984 wl=0.917
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v17_sniper_eth', 'ETH', '60-80', 'UP', 0.88, 1, 823, 64, 0.9844, 0.9167, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- ETH v18 100-140 DN  n=167 WR=0.892 wl=0.836
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v18_t180_eth', 'ETH', '100-140', 'DN', 0.7, 1, 823, 167, 0.8922, 0.8361, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- ETH v18 100-140 UP  n=62 WR=0.952 wl=0.867
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v18_t180_eth', 'ETH', '100-140', 'UP', 0.76, 1, 823, 62, 0.9516, 0.8671, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- ETH v18 160-180 DN  n=26 WR=0.962 wl=0.811
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v18_t180_eth', 'ETH', '160-180', 'DN', 0.72, 1, 823, 26, 0.9615, 0.8111, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- ETH v18 160-180 UP  n=58 WR=0.914 wl=0.814
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v18_t180_eth', 'ETH', '160-180', 'UP', 0.72, 1, 823, 58, 0.9138, 0.8136, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- ETH v18 200-220 DN  n=50 WR=0.860 wl=0.738
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v18_t180_eth', 'ETH', '200-220', 'DN', 0.7, 1, 823, 50, 0.8600, 0.7381, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- ETH v18 60-80 DN  n=50 WR=0.940 wl=0.838
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v18_t180_eth', 'ETH', '60-80', 'DN', 0.76, 1, 823, 50, 0.9400, 0.8378, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- ETH v18 60-80 UP  n=123 WR=0.951 wl=0.898
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v18_t180_eth', 'ETH', '60-80', 'UP', 0.76, 1, 823, 123, 0.9512, 0.8977, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- ETH v20 100-140 DN  n=149 WR=0.859 wl=0.794
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v20_adaptive_early_eth', 'ETH', '100-140', 'DN', 0.76, 1, 823, 149, 0.8591, 0.7941, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- ETH v20 100-140 UP  n=111 WR=0.883 wl=0.810
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v20_adaptive_early_eth', 'ETH', '100-140', 'UP', 0.74, 1, 823, 111, 0.8829, 0.8099, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- ETH v20 160-180 DN  n=132 WR=0.780 wl=0.702
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v20_adaptive_early_eth', 'ETH', '160-180', 'DN', 0.76, 1, 823, 132, 0.7803, 0.7023, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- ETH v20 60-80 DN  n=73 WR=0.932 wl=0.849
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v20_adaptive_early_eth', 'ETH', '60-80', 'DN', 0.82, 1, 823, 73, 0.9315, 0.8495, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- ETH v20 60-80 UP  n=106 WR=0.953 wl=0.894
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v20_adaptive_early_eth', 'ETH', '60-80', 'UP', 0.78, 1, 823, 106, 0.9528, 0.8943, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- XRP v16 100-140 DN  n=105 WR=0.876 wl=0.800
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v16_pure_xrp', 'XRP', '100-140', 'DN', 0.8, 1, 823, 105, 0.8762, 0.7996, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- XRP v16 100-140 UP  n=25 WR=0.960 wl=0.805
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v16_pure_xrp', 'XRP', '100-140', 'UP', 0.84, 1, 823, 25, 0.9600, 0.8046, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- XRP v16 160-180 DN  n=126 WR=0.810 wl=0.732
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v16_pure_xrp', 'XRP', '160-180', 'DN', 0.7, 1, 823, 126, 0.8095, 0.7322, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- XRP v16 60-80 DN  n=39 WR=1.000 wl=0.910
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v16_pure_xrp', 'XRP', '60-80', 'DN', 0.88, 1, 823, 39, 1.0000, 0.9103, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- XRP v16 60-80 UP  n=36 WR=0.917 wl=0.782
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v16_pure_xrp', 'XRP', '60-80', 'UP', 0.84, 1, 823, 36, 0.9167, 0.7817, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- XRP v17 100-140 DN  n=72 WR=0.917 wl=0.830
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v17_sniper_xrp', 'XRP', '100-140', 'DN', 0.82, 1, 823, 72, 0.9167, 0.8299, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- XRP v17 100-140 UP  n=21 WR=0.952 wl=0.773
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v17_sniper_xrp', 'XRP', '100-140', 'UP', 0.88, 1, 823, 21, 0.9524, 0.7733, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- XRP v17 160-180 DN  n=68 WR=0.882 wl=0.785
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v17_sniper_xrp', 'XRP', '160-180', 'DN', 0.78, 1, 823, 68, 0.8824, 0.7846, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- XRP v17 160-180 UP  n=93 WR=0.796 wl=0.703
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v17_sniper_xrp', 'XRP', '160-180', 'UP', 0.7, 1, 823, 93, 0.7957, 0.7028, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- XRP v17 200-220 DN  n=73 WR=0.836 wl=0.734
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v17_sniper_xrp', 'XRP', '200-220', 'DN', 0.76, 1, 823, 73, 0.8356, 0.7343, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- XRP v17 60-80 DN  n=65 WR=1.000 wl=0.944
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v17_sniper_xrp', 'XRP', '60-80', 'DN', 0.86, 1, 823, 65, 1.0000, 0.9442, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- XRP v17 60-80 UP  n=53 WR=0.887 wl=0.774
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v17_sniper_xrp', 'XRP', '60-80', 'UP', 0.82, 1, 823, 53, 0.8868, 0.7742, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- XRP v18 100-140 DN  n=97 WR=0.928 wl=0.858
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v18_t180_xrp', 'XRP', '100-140', 'DN', 0.82, 1, 823, 97, 0.9278, 0.8585, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- XRP v18 100-140 UP  n=75 WR=0.867 wl=0.772
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v18_t180_xrp', 'XRP', '100-140', 'UP', 0.76, 1, 823, 75, 0.8667, 0.7717, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- XRP v18 160-180 DN  n=24 WR=0.958 wl=0.798
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v18_t180_xrp', 'XRP', '160-180', 'DN', 0.86, 1, 823, 24, 0.9583, 0.7976, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- XRP v18 200-220 DN  n=84 WR=0.810 wl=0.713
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v18_t180_xrp', 'XRP', '200-220', 'DN', 0.74, 1, 823, 84, 0.8095, 0.7128, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- XRP v18 60-80 DN  n=33 WR=1.000 wl=0.896
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v18_t180_xrp', 'XRP', '60-80', 'DN', 0.9, 1, 823, 33, 1.0000, 0.8957, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- XRP v18 60-80 UP  n=33 WR=0.939 wl=0.804
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v18_t180_xrp', 'XRP', '60-80', 'UP', 0.88, 1, 823, 33, 0.9394, 0.8039, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- XRP v20 100-140 DN  n=124 WR=0.903 wl=0.838
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v20_adaptive_early_xrp', 'XRP', '100-140', 'DN', 0.82, 1, 823, 124, 0.9032, 0.8384, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- XRP v20 100-140 UP  n=104 WR=0.837 wl=0.754
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v20_adaptive_early_xrp', 'XRP', '100-140', 'UP', 0.62, 1, 823, 104, 0.8365, 0.7537, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- XRP v20 160-180 DN  n=28 WR=0.929 wl=0.774
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v20_adaptive_early_xrp', 'XRP', '160-180', 'DN', 0.84, 1, 823, 28, 0.9286, 0.7735, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- XRP v20 60-80 DN  n=45 WR=0.978 wl=0.884
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v20_adaptive_early_xrp', 'XRP', '60-80', 'DN', 0.9, 1, 823, 45, 0.9778, 0.8843, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();
-- XRP v20 60-80 UP  n=38 WR=0.921 wl=0.792
INSERT INTO strategy_runtime_overrides (strategy_id, asset, eval_offset_band, direction, prob_threshold, shadow_only, source_hub_note, source_cell_n, source_cell_wr, source_cell_wilson, created_at) VALUES ('tickformer_v20_adaptive_early_xrp', 'XRP', '60-80', 'UP', 0.82, 1, 823, 38, 0.9211, 0.7920, NOW()) ON CONFLICT (strategy_id, asset, eval_offset_band, direction) DO UPDATE SET prob_threshold=EXCLUDED.prob_threshold, shadow_only=EXCLUDED.shadow_only, source_cell_n=EXCLUDED.source_cell_n, source_cell_wr=EXCLUDED.source_cell_wr, source_cell_wilson=EXCLUDED.source_cell_wilson, source_hub_note=EXCLUDED.source_hub_note, updated_at=NOW();

COMMIT;

-- SUMMARY: 49 override rows
-- Per (asset, variant):
--   ETH v16: 7 bands×sides
--   ETH v17: 7 bands×sides
--   ETH v18: 7 bands×sides
--   ETH v20: 5 bands×sides
--   XRP v16: 5 bands×sides
--   XRP v17: 7 bands×sides
--   XRP v18: 6 bands×sides
--   XRP v20: 5 bands×sides
