[build]
dockerfilePath = "data-collector/Dockerfile"
watchPatterns = ["data-collector/**"]

[build.buildContext]
context = "data-collector"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
